#!/usr/bin/env sh
#
# The MIT License
#
# Copyright (c) 2016 Gregory L. Dietsche <greg@gregd.org>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#

if [ $# -lt 2 ]; then
	echo Usage: zautosnap.sh zfsFileSystem SnapShotLabel [MaxSnapsToKeep]
	echo If MaxSnapsToKeep is not specified, then no pruning will be done.
	exit
fi

#Create the snapshot
if [ "$3" -ne "0" ]; then
	zfs snapshot -r ${1}@ZAutoSnap_${2}_`date +"%Y-%m-%d_%T"`
fi

#Prune snapshot(s) if necessary / requested
if [ -n "$3" ]; then
	for pool in `zfs list -o name -t volume,filesystem | grep ^$1`
	do
		SNAPS=`zfs list -o name -S creation -t snapshot | grep $pool\@ZAutoSnap_$2_`
		COUNTER=0
		for snap in $SNAPS
		do
			COUNTER=`expr ${COUNTER} + 1`
			if [ "$COUNTER" -gt "$3" ]; then
				zfs destroy $snap &
			fi
		done
	done
fi
exit 0
